//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyCompany("Majid Al Futtaim - Global Solutions")]
[assembly: AssemblyProduct("Microsoft Dynamics 365 Commerce - Majid Al Futtaim Customizations")]
[assembly: AssemblyCopyright("Copyright @ 2023")]
[assembly: AssemblyVersion("100.0.37.114")]
[assembly: AssemblyFileVersion("100.0.37.114")]

// Generated by the MSBuild WriteCodeFragment class.

